apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-template-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/template-gitops/namespace
    repoURL: https://github.com/cloud-native-toolkit-test/terraform-gitops-ocp4
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
